# Generated by Django 4.0.1 on 2022-03-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0035_alter_responsibility_primary_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('primary_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_responsibilities', to='people.employee')),
                ('secondary_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_responsibilities', to='people.employee')),
                ('tags', models.ManyToManyField(to='responsibilities.ResponsibilityTag')),
            ],
            options={
                'verbose_name': 'Responsibility',
                'verbose_name_plural': 'Responsibilities',
                'ordering': ['name'],
            },
        ),
    ]
