# Generated by Django 4.0.1 on 2022-04-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0038_alter_deskreservation_desk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('S', 'Schaefers'), ('P', 'Park Place')], default='S', max_length=1, verbose_name='building')),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('lead', models.BooleanField(default=False)),
                ('ergonomic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['building', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='DeskReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='check-in datetime')),
                ('check_out', models.DateTimeField(null=True, verbose_name='check-out datetime')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='people.desk')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_reservations', to='people.employee')),
            ],
            options={
                'verbose_name': 'Desk Reservation',
                'verbose_name_plural': 'Desk Reservations',
            },
        ),
    ]
