# Generated by Django 4.0.1 on 2022-04-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_migrate_desk_reservations_to_app'),
        ('deskreservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deskreservation',
            options={'ordering': ['-pk'], 'verbose_name': 'Desk Reservation', 'verbose_name_plural': 'Desk Reservations'},
        ),
        migrations.AlterField(
            model_name='deskreservation',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='deskreservation.desk'),
        ),
        migrations.CreateModel(
            name='DeskHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('U', 'Tuesday'), ('W', 'Wednesday'), ('H', 'Thursday'), ('F', 'Friday')], max_length=1, verbose_name='day')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='deskreservation.desk')),
                ('employees', models.ManyToManyField(related_name='desk_holds', to='people.Employee')),
            ],
            options={
                'unique_together': {('desk', 'day')},
            },
        ),
    ]
