# Generated by Django 4.2.11 on 2024-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskreservation', '0002_alter_deskreservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskhold',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
