# Generated by Django 4.2.4 on 2024-12-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskreservation', '0003_deskhold_active_alter_desk_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskhold',
            name='dates',
            field=models.JSONField(blank=True, default=list, help_text='Format: YYYY-MM-DD. e.g. ["2025-01-30", "2025-01-31"]', null=True, verbose_name='dates'),
        ),
        migrations.AlterField(
            model_name='deskhold',
            name='day',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('U', 'Tuesday'), ('W', 'Wednesday'), ('H', 'Thursday'), ('F', 'Friday')], max_length=1, null=True, verbose_name='day'),
        ),
    ]
