# Generated by Django 4.2.11 on 2024-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskreservation', '0003_alter_desk_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskhold',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
