# Generated by Django 4.0.1 on 2023-02-09 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0044_employee_email_opt_out_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('LINK', 'Navigate to Link'), ('API', 'Make API call'), ('EMAIL', 'Send an email')], max_length=5, null=True, verbose_name='action type')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Return'), ('C', 'Change/Modify'), ('E', 'Exit')], max_length=1, null=True, verbose_name='transition type')),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('employee_first_name', models.CharField(blank=True, max_length=50)),
                ('employee_middle_initial', models.CharField(blank=True, max_length=1)),
                ('employee_last_name', models.CharField(blank=True, max_length=50)),
                ('employee_preferred_name', models.CharField(blank=True, max_length=100)),
                ('employee_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, choices=[('CLSD', 'CLSD'), ('CLID', 'CLID')], max_length=4)),
                ('employee_email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('fte', models.FloatField(blank=True, default=1.0)),
                ('salary_range', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bilingual', models.BooleanField(default=False)),
                ('transition_date', models.DateTimeField(blank=True, null=True)),
                ('preliminary_hire', models.BooleanField(default=False)),
                ('delete_profile', models.BooleanField(default=False)),
                ('office_location', models.CharField(choices=[('CG', 'Cottage Grove'), ('FL', 'Florence'), ('JC', 'Junction City'), ('OA', 'Oakridge'), ('P4', 'PPB - 4th Floor'), ('P5', 'PPB - 5th Floor'), ('SB', 'Schaefers - Basement'), ('S1', 'Schaefers - 1st Floor'), ('S2', 'Schaefers - 2nd Floor'), ('S3', 'Schaefers - 3rd Floor'), ('SM', 'Senior Meals Site'), ('VE', 'Veneta')], max_length=3)),
                ('cubicle_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('union_affiliation', models.CharField(choices=[('N', 'Non-Represented'), ('E', 'EA'), ('S', 'SEIU'), ('M', 'Management')], max_length=1)),
                ('teleworking', models.BooleanField(default=False)),
                ('desk_phone', models.BooleanField(default=False)),
                ('current_phone', models.CharField(blank=True, max_length=8)),
                ('new_phone', models.CharField(blank=True, max_length=8)),
                ('load_code', models.CharField(blank=True, max_length=50)),
                ('should_delete', models.BooleanField(default=False)),
                ('reassign_to', models.CharField(blank=True, max_length=50)),
                ('business_cards', models.BooleanField(default=False)),
                ('prox_card_needed', models.BooleanField(default=False)),
                ('prox_card_returned', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('access_emails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_emails_after_transitions', to='people.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_transitions', to='people.employee')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter_of_transitions', to='people.employee')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.unitorprogram')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workflow_start', models.BooleanField(default=False, help_text='Start this process when a workflow begins.')),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('members', models.ManyToManyField(blank=True, related_name='workflow_roles', to='people.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in admin Process detail')),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('choices_prompt', models.CharField(blank=True, help_text='The prompt for when there are multiple next step choices', max_length=200)),
                ('completion_action', models.ForeignKey(blank=True, help_text='Action to trigger as this step completes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.action')),
                ('next_step', models.ForeignKey(blank=True, help_text='The next step, when there is only one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.step')),
                ('optional_actions', models.ManyToManyField(blank=True, related_name='triggering_steps', to='workflows.Action')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.process')),
                ('role', models.ForeignKey(blank=True, help_text='The set of employees responsible for completing this step', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.role')),
                ('trigger_processes', models.ManyToManyField(blank=True, related_name='triggering_steps', to='workflows.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('role', models.ForeignKey(blank=True, help_text='The set of employees with full admin access to this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.role')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.employeetransition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.employee')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.processinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.step')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StepChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in admin Step detail')),
                ('choice_text', models.CharField(max_length=100)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.step')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_step_choices', to='workflows.step')),
            ],
        ),
        migrations.AddField(
            model_name='processinstance',
            name='current_step_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.stepinstance'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.process'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowinstance'),
        ),
        migrations.AddField(
            model_name='process',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The set of employees with full admin access to this process', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.role'),
        ),
        migrations.AddField(
            model_name='process',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='workflows.workflow'),
        ),
    ]
