# Generated by Django 4.0.1 on 2022-09-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0043_employee_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasTimeStampsMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('members', models.ManyToManyField(blank=True, related_name='workflow_roles', to='people.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in admin Process detail')),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('choices_prompt', models.CharField(blank=True, help_text='The prompt for when there are multiple next step choices', max_length=200)),
                ('next_step', models.ForeignKey(blank=True, help_text='The next step, when there is only one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.step')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.process')),
                ('role', models.ForeignKey(blank=True, help_text='The set of employees responsible for completing this step', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.role')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('hastimestampsmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.hastimestampsmixin')),
            ],
            bases=('workflows.hastimestampsmixin',),
        ),
        migrations.CreateModel(
            name='StepChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in admin Step detail')),
                ('choice_text', models.CharField(max_length=100)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.step')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_step_choices', to='workflows.step')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='workflows.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('hastimestampsmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.hastimestampsmixin')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            bases=('workflows.hastimestampsmixin',),
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('hastimestampsmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.hastimestampsmixin')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.employee')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.processinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.step')),
            ],
            bases=('workflows.hastimestampsmixin',),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='current_step_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.stepinstance'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.process'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowinstance'),
        ),
    ]
