# Generated by Django 4.0.1 on 2023-01-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processinstance',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='process',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The set of employees with full admin access to this process', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.role'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The set of employees with full admin access to this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.role'),
        ),
    ]
