# Generated by Django 4.0.1 on 2023-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetransition',
            name='new_phone',
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='phone_request',
            field=models.CharField(blank=True, choices=[('NN', 'New number needed'), ('RP', 'Remove phone'), ('DN', 'Delete number'), ('RT', 'Reassign to:'), ('CN', 'Change name display to:'), ('DV', 'Delete voicemail box')], max_length=2),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='phone_request_data',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='current_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
