# Generated by Django 4.0.1 on 2023-01-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_processinstance_options_alter_workflow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='trigger_processes',
            field=models.ManyToManyField(blank=True, related_name='triggering_steps', to='workflows.Process'),
        ),
    ]
