# Generated by Django 4.0.1 on 2023-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_remove_employeetransition_new_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='office_location',
            field=models.CharField(choices=[('CG', 'Cottage Grove'), ('FL', 'Florence'), ('JC', 'Junction City'), ('OA', 'Oakridge'), ('P4', 'PPB - 4th Floor'), ('P5', 'PPB - 5th Floor'), ('SB', 'Schaefers - Basement'), ('S1', 'Schaefers - 1st Floor'), ('S2', 'Schaefers - 2nd Floor'), ('S3', 'Schaefers - 3rd Floor'), ('SM', 'Senior Meals Site'), ('VE', 'Veneta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='phone_request',
            field=models.CharField(blank=True, choices=[('NN', 'New number needed'), ('RP', 'Remove phone'), ('DN', 'Delete number'), ('RT', 'Reassign to:'), ('CN', 'Change name display to:'), ('DV', 'Delete voicemail box')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='type',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Return'), ('C', 'Change/Modify'), ('E', 'Exit')], max_length=20, null=True, verbose_name='transition type'),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='union_affiliation',
            field=models.CharField(choices=[('N', 'Non-Represented'), ('E', 'EA'), ('S', 'SEIU'), ('M', 'Management')], max_length=20),
        ),
    ]
