# Generated by Django 4.0.1 on 2023-01-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_step_trigger_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='workflow_start',
            field=models.BooleanField(default=False, help_text='Start this process when a workflow begins.'),
        ),
    ]
