# Generated by Django 4.0.1 on 2023-03-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_employeetransition_office_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
