# Generated by Django 4.0.1 on 2023-01-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_process_workflow_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('L', 'Navigate to Link'), ('A', 'Make API call'), ('E', 'Send an email')], max_length=1, null=True, verbose_name='action type')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
