# Generated by Django 4.1.7 on 2023-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='office_location',
            field=models.CharField(choices=[('CG', 'Cottage Grove'), ('FL', 'Florence'), ('JC', 'Junction City'), ('OA', 'Oakridge'), ('P4', 'PPB - 4th Floor'), ('P5', 'PPB - 5th Floor'), ('SB', 'Schaefers - Basement'), ('S1', 'Schaefers - 1st Floor'), ('S2', 'Schaefers - 2nd Floor'), ('S3', 'Schaefers - 3rd Floor'), ('SM', 'Senior Meals Site'), ('VE', 'Veneta')], max_length=30),
        ),
    ]
