# Generated by Django 4.0.1 on 2023-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_step_completion_action_step_optional_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, choices=[('LINK', 'Navigate to Link'), ('API', 'Make API call'), ('EMAIL', 'Send an email')], max_length=5, null=True, verbose_name='action type'),
        ),
    ]
