# Generated by Django 4.1.7 on 2023-05-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_employee_temporary'),
        ('workflows', '0006_remove_employeetransition_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.jobtitle'),
        ),
    ]
