# Generated by Django 4.1.7 on 2023-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_employeetransition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='computer_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='computer_gl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='computer_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Repurposed', 'Repurposed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='office_location',
            field=models.CharField(blank=True, choices=[('Cottage Grove', 'Cottage Grove'), ('Florence', 'Florence'), ('Junction City', 'Junction City'), ('Oakridge', 'Oakridge'), ('PPB - 4th Floor', 'PPB - 4th Floor'), ('PPB - 5th Floor', 'PPB - 5th Floor'), ('Schaefers - Basement', 'Schaefers - Basement'), ('Schaefers - 1st Floor', 'Schaefers - 1st Floor'), ('Schaefers - 2nd Floor', 'Schaefers - 2nd Floor'), ('Schaefers - 3rd Floor', 'Schaefers - 3rd Floor'), ('Senior Meals Site', 'Senior Meals Site'), ('Veneta', 'Veneta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='phone_request',
            field=models.CharField(blank=True, choices=[('New number needed', 'New number needed'), ('Remove phone', 'Remove phone'), ('Delete number', 'Delete number'), ('Reassign to:', 'Reassign to:'), ('Change name display to:', 'Change name display to:'), ('Delete voicemail box', 'Delete voicemail box')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Return', 'Return'), ('Change/Modify', 'Change/Modify'), ('Exit', 'Exit')], max_length=20, null=True, verbose_name='transition type'),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='union_affiliation',
            field=models.CharField(blank=True, choices=[('Non-Represented', 'Non-Represented'), ('EA', 'EA'), ('SEIU', 'SEIU'), ('Management', 'Management')], max_length=20),
        ),
    ]
