# Generated by Django 4.0.1 on 2023-02-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_employee_email_opt_out_all_and_more'),
        ('workflows', '0007_alter_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Return'), ('C', 'Change/Modify'), ('E', 'Exit')], max_length=1, null=True, verbose_name='transition type')),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('employee_first_name', models.CharField(blank=True, max_length=50)),
                ('employee_middle_initial', models.CharField(blank=True, max_length=1)),
                ('employee_last_name', models.CharField(blank=True, max_length=50)),
                ('employee_preferred_name', models.CharField(blank=True, max_length=100)),
                ('employee_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, choices=[('CLSD', 'CLSD'), ('CLID', 'CLID')], max_length=4)),
                ('employee_email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('fte', models.FloatField(blank=True, default=1.0)),
                ('salary_range', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bilingual', models.BooleanField(default=False)),
                ('transition_date', models.DateTimeField(blank=True, null=True)),
                ('delete_profile', models.BooleanField(default=False)),
                ('office_location', models.CharField(choices=[('CG', 'Cottage Grove'), ('FL', 'Florence'), ('JC', 'Junction City'), ('OA', 'Oakridge'), ('P4', 'PPB - 4th Floor'), ('P5', 'PPB - 5th Floor'), ('SB', 'Schaefers - Basement'), ('S1', 'Schaefers - 1st Floor'), ('S2', 'Schaefers - 2nd Floor'), ('S3', 'Schaefers - 3rd Floor'), ('SM', 'Senior Meals Site'), ('VE', 'Veneta')], max_length=3)),
                ('cubicle_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('union_affiliation', models.CharField(choices=[('N', 'Non-Represented'), ('E', 'EA'), ('S', 'SEIU'), ('M', 'Management')], max_length=1)),
                ('teleworking', models.BooleanField(default=False)),
                ('preliminary_hire', models.BooleanField(default=False)),
                ('desk_phone', models.BooleanField(default=False)),
                ('current_phone', models.CharField(blank=True, max_length=8)),
                ('new_phone', models.CharField(blank=True, max_length=8)),
                ('load_code', models.CharField(blank=True, max_length=50)),
                ('delete', models.BooleanField(default=False)),
                ('reassign_to', models.CharField(blank=True, max_length=50)),
                ('business_cards', models.BooleanField(default=False)),
                ('prox_card_needed', models.BooleanField(default=False)),
                ('prox_card_returned', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('access_emails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_emails_after_transitions', to='people.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_transitions', to='people.employee')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter_of_transitions', to='people.employee')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.unitorprogram')),
            ],
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='transition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.employeetransition'),
        ),
    ]
