# Generated by Django 4.0.1 on 2023-02-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_employeetransition_workflowinstance_transition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetransition',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='employeetransition',
            old_name='delete',
            new_name='should_delete',
        ),
    ]
