# Generated by Django 4.1.7 on 2023-05-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_remove_employeetransition_current_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='cubicle_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
