# Generated by Django 4.1.7 on 2023-06-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_transitionchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='gas_pin_needed',
            field=models.BooleanField(default=False, verbose_name='Gas PIN needed'),
        ),
    ]
