# Generated by Django 4.1.7 on 2023-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_employeetransition_cubicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='cell_phone',
            field=models.BooleanField(default=False),
        ),
    ]
