# Generated by Django 4.1.7 on 2023-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_employeetransition_second_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
