# Generated by Django 4.1.7 on 2023-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_workflowinstance_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
