# Generated by Django 4.1.7 on 2023-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_workflowinstance_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='lwop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='lwop_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
