# Generated by Django 4.1.7 on 2023-08-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_alter_employeetransition_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='fiscal_field',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='salary_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
