# Generated by Django 4.2.7 on 2023-12-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_employeetransition_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.process'),
        ),
    ]
