# Generated by Django 4.2.7 on 2023-12-22 21:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_alter_step_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='percent_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='percent_complete',
            field=models.IntegerField(default=0),
        ),
    ]
