# Generated by Django 4.2.7 on 2024-01-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_processinstance_percent_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='system_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
