# Generated by Django 4.2.11 on 2024-04-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_employeetransition_system_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='icon',
            field=models.CharField(blank=True, help_text='The name of a Material Design icon', max_length=50),
        ),
        migrations.AddField(
            model_name='workflow',
            name='type',
            field=models.CharField(blank=True, help_text='Short name for the type of workflow, e.g. new, exit', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(help_text='Display name of the workflow', max_length=100),
        ),
    ]
