# Generated by Django 4.2.11 on 2024-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_workflowinstance_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='oregon_access',
            field=models.CharField(choices=[('Not needed', 'Not needed'), ('Desktop', 'Desktop'), ('Remote', 'Remote')], default='Not needed', max_length=10),
        ),
    ]
