# Generated by Django 4.2.11 on 2024-07-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_employeetransition_oregon_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='hours_per_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='schedule',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='worker_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer'), ('Temp Agency', 'Temp Agency'), ('Temp Non-Agency', 'Temp Non-Agency')], default='Employee', max_length=15, verbose_name='worker type'),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='employee_id',
            field=models.CharField(blank=True, choices=[('CLSD', 'CLSD'), ('CLID', 'CLID'), ('None/Non-Employee', 'None/Non-Employee')], max_length=17),
        ),
    ]
