# Generated by Django 4.2.11 on 2024-09-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_employeetransition_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis', to='workflows.workflowinstance'),
        ),
    ]
