# Generated by Django 4.2.11 on 2024-10-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0027_remove_employeetransition_desk_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='mailbox_needed',
            field=models.BooleanField(default=False),
        ),
    ]
