# Generated by Django 4.2.11 on 2024-10-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_employeetransition_mailbox_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepchoice',
            name='trigger_processes',
            field=models.ManyToManyField(blank=True, related_name='triggering_step_choices', to='workflows.process'),
        ),
    ]
