# Generated by Django 4.2.11 on 2024-11-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_stepchoice_trigger_processes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='employeetransition',
            name='prox_card_returned',
        ),
    ]
