# Generated by Django 4.2.11 on 2025-04-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0030_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='worker_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer'), ('Temp Agency', 'Temp Agency'), ('Temp Non-Agency', 'Temp Non-Agency'), ('Contractor', 'Contractor')], default='Employee', max_length=15, verbose_name='worker type'),
        ),
    ]
