# Generated by Django 4.2.11 on 2025-04-30 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0055_prfactorresponseset_performancereview_data_prform_and_more'),
        ('workflows', '0031_alter_employeetransition_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransition',
            name='current_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employee_of_transitions', to='people.employee'),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Return', 'Return'), ('Name Change', 'Name Change'), ('Change/Modify', 'Change/Modify'), ('Exit', 'Exit')], max_length=20, null=True, verbose_name='transition type'),
        ),
    ]
