# Generated by Django 4.2.11 on 2024-08-16 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expensegl',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='dollar amount'),
        ),
        migrations.AlterField(
            model_name='expensecard',
            name='last4',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be 4 digits', regex='^[0-9]{4}$')]),
        ),
    ]
