# Generated by Django 4.2.4 on 2023-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/expenses', verbose_name='receipt')),
            ],
        ),
    ]
