# Generated by Django 4.2.11 on 2024-08-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecard',
            name='last4',
            field=models.CharField(max_length=4),
        ),
    ]
