# Generated by Django 4.2.11 on 2024-08-16 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_expensecard_last4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AlterField(
            model_name='expensecard',
            name='last4',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be 4 digits', regex='^[0-9]{4}$')]),
        ),
    ]
