# Generated by Django 4.2.11 on 2024-04-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0049_jobtitle_active_jobtitle_division'),
        ('purchases', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_of_expenses', to='people.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='gls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_purchased', to='people.employee'),
        ),
    ]
