# Generated by Django 4.2.11 on 2024-08-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_expense_description_expensegl_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
