# Generated by Django 4.2.11 on 2024-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_expense_approval_notes_expense_approver_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='gls',
            field=models.JSONField(blank=True, null=True, verbose_name='GL Codes'),
        ),
    ]
