# Generated by Django 4.2.11 on 2024-08-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_expense_description_alter_expensecard_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegl',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='dollar amount'),
        ),
    ]
