# Generated by Django 4.2.11 on 2024-08-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_expensegl_percent_expense_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approved_at',
        ),
    ]
