# Generated by Django 4.2.11 on 2024-05-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0004_alter_expense_options_alter_expense_gls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approval_notes',
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved')], max_length=16, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_months', to='people.employee')),
            ],
        ),
    ]
