# Generated by Django 4.2.11 on 2024-05-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0004_alter_expense_options_alter_expense_gls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approval_notes',
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('fiscal_approved', 'Fiscal Approved'), ('fiscal_denied', 'Fiscal Denied')], default='draft', max_length=17),
        ),
        migrations.AlterField(
            model_name='expense',
            name='gls',
            field=models.JSONField(blank=True, default=list, verbose_name='GL Codes'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='job',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExpenseMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('fiscal_approved', 'Fiscal Approved'), ('fiscal_denied', 'Fiscal Denied')], default='draft', max_length=17)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_of_expense_month', to='people.employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_months', to='people.employee')),
            ],
            options={
                'ordering': ['pk'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
