# Generated by Django 4.2.11 on 2024-09-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0051_employee_email_opt_out_expenses_all_and_more'),
        ('purchases', '0004_remove_expense_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMonthLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_month_locks', to='people.employee')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
