# Generated by Django 4.2.11 on 2024-05-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0004_alter_expense_options_alter_expense_gls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approval_notes',
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('finance_approved', 'Finance Approved')], default='draft', max_length=17),
        ),
        migrations.CreateModel(
            name='ExpenseMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('finance_approved', 'Finance Approved')], default='draft', max_length=17)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_months', to='people.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
