# Generated by Django 4.2.11 on 2024-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_remove_expense_approval_notes_expense_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensemonth',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('finance_approved', 'Finance Approved'), ('finance_denied', 'Finance Denied')], default='draft', max_length=17),
        ),
        migrations.AlterField(
            model_name='expensemonth',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('finance_approved', 'Finance Approved'), ('finance_denied', 'Finance Denied')], default='draft', max_length=17),
        ),
    ]
