# Generated by Django 4.2.11 on 2024-07-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0005_remove_expense_approval_notes_expense_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.IntegerField()),
                ('shared', models.BooleanField(default=False)),
                ('requires_director_approval', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_cards', to='people.employee')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_of_cards', to='people.employee')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='purchases.expensecard')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RenameField(
            model_name='expensemonth',
            old_name='approved_at',
            new_name='fiscal_approved_at',
        ),
        migrations.RenameField(
            model_name='expensemonth',
            old_name='approver',
            new_name='fiscal_approver',
        ),
        migrations.RenameField(
            model_name='expensemonth',
            old_name='employee',
            new_name='purchaser',
        ),
        migrations.AlterUniqueTogether(
            name='expensemonth',
            unique_together={('purchaser', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='gls',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='purchaser',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='purchases.expensemonth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='director_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='fiscal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='submitter_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('director_approved', 'Director Approved'), ('director_denied', 'Director Denied'), ('fiscal_approved', 'Fiscal Approved'), ('fiscal_denied', 'Fiscal Denied')], default='draft', max_length=17),
        ),
        migrations.AlterField(
            model_name='expensemonth',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('director_approved', 'Director Approved'), ('director_denied', 'Director Denied'), ('fiscal_approved', 'Fiscal Approved'), ('fiscal_denied', 'Fiscal Denied')], default='draft', max_length=17),
        ),
        migrations.CreateModel(
            name='ExpenseStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.expensestatement')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver_note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_gls', to='people.employee')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gls', to='purchases.expense')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_months', to='purchases.expensecard'),
        ),
    ]
