# Generated by Django 4.2.11 on 2024-05-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0006_alter_expensemonth_options_alter_expense_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemonth',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_of_expense_month', to='people.employee'),
        ),
    ]
