# Generated by Django 4.2.11 on 2024-06-04 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0006_expense_description_expense_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='gls',
        ),
        migrations.CreateModel(
            name='ExpenseGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_gls', to='people.employee')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gls', to='purchases.expense')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
