# Generated by Django 4.2.11 on 2024-12-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegl',
            name='job',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
