# Generated by Django 4.2.11 on 2024-06-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0007_remove_expense_approver_remove_expense_gls_expensegl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemonth',
            old_name='employee',
            new_name='purchaser',
        ),
        migrations.AlterUniqueTogether(
            name='expensemonth',
            unique_together={('purchaser', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='purchaser',
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='purchases.expensemonth'),
            preserve_default=False,
        ),
    ]
