# Generated by Django 4.2.11 on 2024-12-03 00:59

from django.db import migrations


def migrate_job_numbers(apps, schema_editor):
    # Move job number field from Expense to ExpenseGL
    Expense = apps.get_model("purchases", "Expense")
    for expense in Expense.objects.all():
        if expense.job:
            job = expense.job
            for gl in expense.gls.all():
                gl.job = job
                gl.save()
 

class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_expensegl_job'),
    ]

    operations = [
        migrations.RunPython(migrate_job_numbers)
    ]
