# Generated by Django 4.2.11 on 2024-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_rename_employee_expensemonth_purchaser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegl',
            name='approver_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='fiscal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='submitter_note',
            field=models.TextField(blank=True),
        ),
    ]
