# Generated by Django 4.2.11 on 2024-12-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_migrate_job_from_expense_to_gl'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegl',
            name='activity',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
