# Generated by Django 4.2.11 on 2025-01-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_expensegl_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='job',
        ),
    ]
