# Generated by Django 4.2.11 on 2024-06-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0010_expensecard_expensestatement_expensestatementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecard',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_cards', to='people.employee'),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_months', to='purchases.expensecard'),
        ),
    ]
