# Generated by Django 4.2.11 on 2025-02-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_remove_expense_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemonth',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
