# Generated by Django 4.2.11 on 2025-02-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_remove_expense_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemonth',
            name='approved_as_of',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='denier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
