# Generated by Django 4.2.11 on 2024-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecard',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
