# Generated by Django 4.2.11 on 2024-06-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_workflowoptions_employee_workflow_options'),
        ('purchases', '0013_expensecard_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecard',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_of_cards', to='people.employee'),
        ),
        migrations.AddField(
            model_name='expensecard',
            name='requires_director_approval',
            field=models.BooleanField(default=False),
        ),
    ]
