# Generated by Django 4.2.11 on 2024-06-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_expensecard_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemonth',
            name='director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='director_note',
            field=models.TextField(blank=True),
        ),
    ]
