# Generated by Django 4.2.11 on 2024-06-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_expensemonth_director_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('director_approved', 'Director Approved'), ('director_denied', 'Director Denied'), ('fiscal_approved', 'Fiscal Approved'), ('fiscal_denied', 'Fiscal Denied')], default='draft', max_length=17),
        ),
        migrations.AlterField(
            model_name='expensemonth',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approver_approved', 'Approver Approved'), ('approver_denied', 'Approver Denied'), ('director_approved', 'Director Approved'), ('director_denied', 'Director Denied'), ('fiscal_approved', 'Fiscal Approved'), ('fiscal_denied', 'Fiscal Denied')], default='draft', max_length=17),
        ),
    ]
