# Generated by Django 4.2.11 on 2024-07-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_alter_expense_status_alter_expensemonth_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemonth',
            old_name='approved_at',
            new_name='fiscal_approved_at',
        ),
        migrations.RenameField(
            model_name='expensemonth',
            old_name='approver',
            new_name='fiscal_approver',
        ),
    ]
