# Generated by Django 3.2.5 on 2021-08-26 23:36

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Security Message',
                'verbose_name_plural': 'Security Messages',
                'ordering': ['active', '-pk'],
                'get_latest_by': 'date',
            },
        ),
    ]
