# Generated by Django 4.2.4 on 2023-09-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_state_zipcode_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymessage',
            name='num_active_employees',
            field=models.IntegerField(default=0, verbose_name='number of active employees at time of creation'),
        ),
    ]
