# Generated by Django 4.2.7 on 2023-12-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_securitymessage_num_active_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedipaddress',
            name='address_range_end',
            field=models.GenericIPAddressField(blank=True, help_text='Optional. If you want to allow a range of IP addresses, enter the end of the range here.', null=True),
        ),
    ]
