# Generated by Django 4.2.11 on 2025-05-13 20:31

from django.db import migrations, models
import mainsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_trustedipaddress_address_range_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
            bases=(models.Model, mainsite.models.ActiveMixin),
        ),
    ]
