# Generated by Django 3.1 on 2020-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='upper_manager_note',
            field=models.TextField(default='', verbose_name='upper manager note'),
        ),
    ]
