# Generated by Django 3.0.7 on 2020-09-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_performanceevaluation_upper_manager_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('N', 'Needs evaluation'), ('EW', 'Evaluation written and date for discussion set'), ('EC', 'Evaluation discussed with employee'), ('ED', 'Evaluation denied'), ('EA', 'Evaluation approved'), ('EP', 'Evaluation processed by HR')], default='N', max_length=2, verbose_name='review status'),
        ),
    ]
