# Generated by Django 3.0.7 on 2020-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200831_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='upper_manager_note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='upper manager note'),
        ),
    ]
