# Generated by Django 3.0.7 on 2020-10-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20201007_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='evaluation',
            field=models.TextField(blank=True, null=True, verbose_name='performance evaluation'),
        ),
    ]
