# Generated by Django 3.0.7 on 2020-10-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20201014_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='discussion_date',
            field=models.DateField(blank=True, null=True, verbose_name='discussion date'),
        ),
    ]
