# Generated by Django 3.0.7 on 2020-10-22 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20201014_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'Job Titles',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='signatur date')),
                ('is_employee', models.BooleanField(default=False, verbose_name='employee signature')),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager signature')),
                ('is_final_signature', models.BooleanField(default=False, verbose_name='final signature')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
            },
        ),
        migrations.CreateModel(
            name='UnitOrProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Division', verbose_name='division')),
            ],
            options={
                'verbose_name': 'Unit/Program',
                'verbose_name_plural': 'Units/Programs',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='date',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='description_reviewed_employee',
            field=models.BooleanField(default=False, verbose_name='position description has been reviewed with employee'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='effective date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_comments_employee',
            field=models.TextField(blank=True, null=True, verbose_name='employee comments'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_goals_employee',
            field=models.TextField(blank=True, null=True, verbose_name='goals for the comind year (employee)'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_goals_manager',
            field=models.TextField(blank=True, null=True, verbose_name='goals for the comind year (manager)'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_opportunities',
            field=models.TextField(blank=True, null=True, verbose_name='opportunities for growth'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_successes',
            field=models.TextField(blank=True, null=True, verbose_name="employee's successes"),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_type',
            field=models.CharField(choices=[('P', 'Probationary evaluation'), ('A', 'Annual evaluation')], default='A', max_length=1, verbose_name='evaluation type'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_analysis',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='analysis and decision-making'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_communication',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='communication'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_dependability',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='dependability and responsibility'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_initiative',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='initiative and creativity'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_interpersonal',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='interpersonal relations'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_job_knowledge',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='job knowledge'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_management',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='project management'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_professionalism',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='professionalism and customer service'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_supervision',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='supervision'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_work_habits',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='work habits'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_work_quality',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='quality of work'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='factor_work_quantity',
            field=models.CharField(choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, verbose_name='quanitity of work'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='period_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='performance period end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='period_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='performance period start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='probationary_evaluation_type',
            field=models.CharField(blank=True, choices=[('P', 'Probationary evaluation'), ('A', 'Annual evaluation')], max_length=1, null=True, verbose_name='evaluation type'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='step_increase',
            field=models.BooleanField(default=True, verbose_name='step increase'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='top_step_bonus',
            field=models.BooleanField(default=False, verbose_name='top step bonus'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='people.Employee', verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('N', 'Needs evaluation'), ('EW', 'Evaluation written'), ('EA', 'Evaluation approved'), ('EP', 'Evaluation processed by HR')], default='N', max_length=2, verbose_name='review status'),
        ),
        migrations.DeleteModel(
            name='PerformanceEvaluation',
        ),
        migrations.AddField(
            model_name='signature',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee'),
        ),
        migrations.AddField(
            model_name='signature',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.PerformanceReview', verbose_name='performance review'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.JobTitle', verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='employee',
            name='unit_or_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.UnitOrProgram', verbose_name='unit/program'),
        ),
    ]
