# Generated by Django 3.0.7 on 2020-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20201022_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='evaluation_type',
            field=models.CharField(blank=True, choices=[('P', 'Probationary evaluation'), ('A', 'Annual evaluation')], default='A', max_length=1, null=True, verbose_name='evaluation type'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='step_increase',
            field=models.BooleanField(null=True, verbose_name='step increase'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='top_step_bonus',
            field=models.BooleanField(null=True, verbose_name='top step bonus'),
        ),
    ]
