# Generated by Django 3.0.7 on 2020-10-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201022_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='probationary_evaluation_type',
            field=models.CharField(blank=True, choices=[('N', 'SEIU (180 day)'), ('N', 'Non-SEIU (6 month)')], max_length=1, null=True, verbose_name='probationary evaluation type'),
        ),
    ]
