# Generated by Django 3.0.7 on 2020-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20201022_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='factor_analysis',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='analysis and decision-making'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_communication',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='communication'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_dependability',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='dependability and responsibility'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_initiative',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='initiative and creativity'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_interpersonal',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='interpersonal relations'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_job_knowledge',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='job knowledge'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_management',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='NA', max_length=2, null=True, verbose_name='project management'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_professionalism',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='professionalism and customer service'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_supervision',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='NA', max_length=2, null=True, verbose_name='supervision'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_work_habits',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='work habits'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_work_quality',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='quality of work'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='factor_work_quantity',
            field=models.CharField(blank=True, choices=[('N', 'Needs Improvement'), ('M', 'Meets Job Requirements'), ('E', 'Exceeds Job Requirements'), ('NA', 'Not Applicable')], default='M', max_length=2, null=True, verbose_name='quanitity of work'),
        ),
    ]
