# Generated by Django 3.0.7 on 2020-10-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20201022_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('N', 'Needs evaluation'), ('EW', 'Evaluation written'), ('EA', 'Evaluation approved up to division director'), ('EP', 'Evaluation processed by HR'), ('ED', 'Evaluation approved by executive director')], default='N', max_length=2, verbose_name='review status'),
        ),
    ]
