# Generated by Django 3.0.7 on 2020-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20201022_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewnote',
            options={'verbose_name': 'Review Note', 'verbose_name_plural': 'Review Notes'},
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='step_increase',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='step increase'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='top_step_bonus',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='top step bonus'),
        ),
    ]
