# Generated by Django 3.0.7 on 2020-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20201029_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_division_director',
            field=models.BooleanField(default=False, verbose_name='is a division director'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_executive_director',
            field=models.BooleanField(default=False, verbose_name='is the executive director'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hr_resources_manager',
            field=models.BooleanField(default=False, verbose_name='is the HR resources manager'),
        ),
    ]
