# Generated by Django 3.0.7 on 2020-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20201030_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_hr_resources_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_hr_manager',
            field=models.BooleanField(default=False, verbose_name='is the HR manager'),
        ),
    ]
