# Generated by Django 3.0.7 on 2020-10-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20201030_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_final_signature',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_manager',
        ),
    ]
