# Generated by Django 3.0.7 on 2020-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20201118_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturereminder',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='most recent reminder date'),
        ),
    ]
