# Generated by Django 3.0.7 on 2020-11-19 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20201118_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturereminder',
            name='next_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='planned reminder date'),
            preserve_default=False,
        ),
    ]
