# Generated by Django 3.0.7 on 2020-12-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20201211_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturereminder',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='reminder date'),
        ),
    ]
