# Generated by Django 3.0.7 on 2021-02-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_performancereview_signed_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='signed_position_description',
            field=models.FileField(blank=True, null=True, upload_to='signed-position-descriptions', verbose_name='signed position description'),
        ),
    ]
