# Generated by Django 3.2.5 on 2021-08-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_employee_viewed_security_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__username'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-pk'], 'verbose_name': 'Performance Review', 'verbose_name_plural': 'Performance Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewnote',
            options={'ordering': ['-pk'], 'verbose_name': 'Review Note', 'verbose_name_plural': 'Review Notes'},
        ),
        migrations.AlterModelOptions(
            name='unitorprogram',
            options={'ordering': ['division__name', 'name'], 'verbose_name': 'Unit/Program', 'verbose_name_plural': 'Units/Programs'},
        ),
    ]
