# Generated by Django 3.2.5 on 2021-08-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
        ('people', '0027_auto_20210826_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedSecurityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='viewed date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee', verbose_name='employee')),
                ('security_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.securitymessage')),
            ],
        ),
    ]
