# Generated by Django 3.2.5 on 2021-09-08 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_viewedsecuritymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleworkApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'Not yet approved'), ('A', 'APPROVED')], default='U', max_length=1, verbose_name='application status')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('program_manager_approve', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='program manager approve')),
                ('hours_onsite', models.TextField(blank=True, null=True, verbose_name='hours onsite')),
                ('telework_location', models.TextField(blank=True, null=True, verbose_name='telework location')),
                ('hours_working', models.TextField(blank=True, null=True, verbose_name='hours working')),
                ('duties', models.TextField(blank=True, null=True, verbose_name='duties')),
                ('communication_when', models.TextField(blank=True, null=True, verbose_name='communication when')),
                ('communication_time', models.TextField(blank=True, null=True, verbose_name='communication time')),
                ('communication_how', models.TextField(blank=True, null=True, verbose_name='communication how')),
                ('equipment_provided_phone', models.BooleanField(default=False, verbose_name='equipment provided phone')),
                ('equipment_provided_laptop', models.BooleanField(default=False, verbose_name='equipment provided laptop')),
                ('equipment_provided_desktop', models.BooleanField(default=False, verbose_name='equipment provided desktop')),
                ('equipment_provided_monitor', models.BooleanField(default=False, verbose_name='equipment provided monitor')),
                ('equipment_provided_access', models.BooleanField(default=False, verbose_name='equipment provided access')),
                ('equipment_provided_other', models.BooleanField(default=False, verbose_name='equipment provided other')),
                ('equipment_provided_other_value', models.TextField(blank=True, null=True, verbose_name='equipment provided other value')),
                ('workspace_checklist_1', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 1')),
                ('workspace_checklist_2', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 2')),
                ('workspace_checklist_3', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 3')),
                ('workspace_checklist_4', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 4')),
                ('workspace_checklist_5', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 5')),
                ('workspace_checklist_6', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 6')),
                ('workspace_checklist_7', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 7')),
                ('workspace_checklist_8', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 8')),
                ('workspace_checklist_9', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 9')),
                ('workspace_checklist_10', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 10')),
                ('workspace_checklist_11', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 11')),
                ('workspace_checklist_12', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='workspace checklist 12')),
                ('emergency_checklist_1', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 1')),
                ('emergency_checklist_2', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 2')),
                ('emergency_checklist_3', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 3')),
                ('ergonomics_checklist_1', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 1')),
                ('ergonomics_checklist_2', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 2')),
                ('ergonomics_checklist_3', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 3')),
                ('ergonomics_checklist_4', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 4')),
                ('ergonomics_checklist_5', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='emergency checklist 5')),
                ('teleworker_comments', models.TextField(blank=True, null=True, verbose_name='teleworker comments')),
                ('manager_comments', models.TextField(blank=True, null=True, verbose_name='manager comments')),
                ('dependent_care_checklist_1', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='dependent care checklist 1')),
                ('dependent_care_documentation', models.FileField(blank=True, null=True, upload_to='uploads/dependent-care-documentation', verbose_name='dependent care documentation')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Telework Application',
                'verbose_name_plural': 'Telework Applications',
                'ordering': ['-pk'],
            },
        ),
    ]
