# Generated by Django 3.2.5 on 2021-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_teleworkapplication_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleworkapplication',
            name='date_approved',
            field=models.DateField(blank=True, null=True, verbose_name='date approved'),
        ),
        migrations.AlterField(
            model_name='teleworkapplication',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('R', 'Ready for signature'), ('A', 'Approved')], default='I', max_length=1, verbose_name='application status'),
        ),
    ]
