# Generated by Django 3.2.5 on 2021-10-12 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_auto_20210922_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('primary_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_responsibilities', to='people.employee')),
                ('secondary_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_responsibilities', to='people.employee')),
            ],
            options={
                'verbose_name': 'Responsibility',
                'verbose_name_plural': 'Responsibilities',
            },
        ),
    ]
