# Generated by Django 4.0.1 on 2022-03-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_desk_deskreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='primary_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_responsibilities_old', to='people.employee'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='secondary_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_responsibilities_old', to='people.employee'),
        ),
    ]
