# Generated by Django 4.0.1 on 2022-02-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_desk_deskreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskreservation',
            name='desk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='people.desk'),
            preserve_default=False,
        ),
    ]
