# Generated by Django 4.0.1 on 2022-03-07 22:10

from django.db import migrations


def migrate_responsibilities(apps, schema_editor):
    # Move responsibilities to new app
    OldResponsibility = apps.get_model('people', 'Responsibility')
    NewResponsibility = apps.get_model('responsibilities', 'Responsibility')
    for r in OldResponsibility.objects.all():
        new_r = NewResponsibility.objects.create(
            name=r.name,
            link=r.link,
            primary_employee=r.primary_employee,
            secondary_employee=r.secondary_employee
        )


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_alter_responsibility_primary_employee_and_more'),
        ('responsibilities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_responsibilities)
    ]
