# Generated by Django 4.0.1 on 2022-04-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_delete_old_responsibility_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskreservation',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_old', to='people.desk'),
        ),
        migrations.AlterField(
            model_name='deskreservation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_reservations_old', to='people.employee'),
        ),
    ]
