# Generated by Django 4.0.1 on 2022-03-07 22:10

from django.db import migrations


def migrate_desks_and_reservations(apps, schema_editor):
    # Move Desk and DeskReservation to new separate app
    OldDesk = apps.get_model('people', 'Desk')
    NewDesk = apps.get_model('deskreservation', 'Desk')
    for d in OldDesk.objects.all():
        NewDesk.objects.create(
            building=d.building,
            floor=d.floor,
            number=d.number,
            active=d.active,
            lead=d.lead,
            ergonomic=d.ergonomic
        )

    OldReservation = apps.get_model('people', 'DeskReservation')
    NewReservation = apps.get_model('deskreservation', 'DeskReservation')
    for r in OldReservation.objects.all():
        NewReservation.objects.create(
            employee=r.employee,
            desk=r.desk,
            check_in=r.check_in,
            check_out=r.check_out
        )


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_alter_deskreservation_desk_and_more'),
        ('deskreservation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_desks_and_reservations)
    ]
