# Generated by Django 4.0.1 on 2022-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='number'),
        ),
    ]
