# Generated by Django 4.0.1 on 2022-08-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0042_populate_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='display name'),
        ),
    ]
