# Generated by Django 4.0.1 on 2022-10-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0043_employee_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_opt_out_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_opt_out_timeoff_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_opt_out_timeoff_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_opt_out_timeoff_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='evaluation_goals_employee',
            field=models.TextField(blank=True, null=True, verbose_name='goals for the coming year (employee)'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='evaluation_goals_manager',
            field=models.TextField(blank=True, null=True, verbose_name='goals for the coming year (manager)'),
        ),
    ]
