# Generated by Django 4.0.1 on 2023-02-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_employee_email_opt_out_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='temporary',
            field=models.BooleanField(default=False, help_text='Employee is temporary or exists for test purposes. They are not present in the payroll system, but should not be deactivated.', verbose_name='temporary employee'),
        ),
    ]
