# Generated by Django 4.1.7 on 2023-06-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_employee_temporary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['name'], 'verbose_name': 'Job Title', 'verbose_name_plural': 'Job Titles'},
        ),
    ]
