# Generated by Django 4.2.7 on 2024-02-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0048_alter_performancereview_action_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.division'),
        ),
    ]
