# Generated by Django 4.2.11 on 2024-04-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_employeetransition_system_change_date'),
        ('people', '0049_jobtitle_active_jobtitle_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Option',
                'verbose_name_plural': 'Workflow Options',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='workflow_options',
            field=models.ManyToManyField(through='people.WorkflowOptions', to='workflows.workflow'),
        ),
    ]
