# Generated by Django 4.2.11 on 2024-09-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0051_employee_email_opt_out_expenses_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_opt_out_workflows_processes',
            field=models.BooleanField(default=False),
        ),
    ]
