# Generated by Django 4.2.11 on 2025-01-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0052_employee_email_opt_out_workflows_processes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewnote',
            name='manager',
        ),
        migrations.AddField(
            model_name='reviewnote',
            name='author',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to='people.employee', verbose_name='author'),
            preserve_default=False,
        ),
    ]
