# Generated by Django 4.2.11 on 2025-02-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0054_remove_reviewnote_date_reviewnote_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRFactorResponseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=list, help_text='Format e.g. ["Good", "Bad", "Ugly"]')),
            ],
            options={
                'verbose_name': 'Performance Review Factor Response Set',
            },
        ),
        migrations.AddField(
            model_name='performancereview',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PRForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('long_responses', models.JSONField(blank=True, default=list, help_text='Format [["Title", "Subtitle"], ...] e.g. [["Strengths", ""], ["Areas for Improvement", "Be nice!"]]', null=True)),
                ('factors_response_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.prfactorresponseset')),
            ],
            options={
                'verbose_name': 'Performance Review Form',
                'ordering': ['-pk'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PRFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('not_applicable_option', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.prform')),
            ],
        ),
        migrations.AddField(
            model_name='performancereview',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.prform'),
        ),
    ]
