# Generated by Django 4.2.11 on 2025-05-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_organization'),
        ('people', '0055_prfactorresponseset_performancereview_data_prform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.organization', verbose_name='organization'),
        ),
    ]
