# Generated by Django 4.2.11 on 2025-04-23 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0055_prfactorresponseset_performancereview_data_prform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfactor',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prfactor',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='people.prform'),
        ),
    ]
