# Generated by Django 4.2.11 on 2025-05-13 20:34

from django.db import migrations

def create_lcog_organization_and_assign_employees(apps, schema_editor):
    Organization = apps.get_model('mainsite', 'Organization')
    Employee = apps.get_model('people', 'Employee')

    # Create the "LCOG" organization
    lcog_org, created = Organization.objects.get_or_create(name="LCOG")

    # Assign all existing employees to the "LCOG" organization
    Employee.objects.update(organization=lcog_org)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0056_division_organization_employee_organization'),
    ]

    operations = [
        migrations.RunPython(create_lcog_organization_and_assign_employees),
    ]